version: '3'

services:

  accounting_db:
    image: 'postgres:14.5'
    container_name: accounting_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accounting
    volumes:
      - ./postgres-data:/var/lib/postgres
    ports:
      - "5432:5432"
